spring:
  application:
    name: PARTYBUILDINTER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/devops?useUnicode=true&characterEncoding=UTF-8
    username: devops
    password: devops
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  dubbo:
    server: true
    application:
      id: live-dubbo-provider
      name: live-dubbo-provider
    registry:
      address: zookeeper://192.168.1.79:2181
    protocol:
      name: dubbo
      port: 20880
    monitor:
      protocol: registry
server:
  port: 8081
  
mybatis:
    mapper-locations: com.cnten.**.*.mapper.*.xml
logging:
  level:
    com:
      looedu:
        mapper: debug